### ISSUE TITLE
 æøå in argument trouble

### ISSUE THREAD

**Issue by sigurd-dev** [cbielow/wintime#1]
Nice program!

If I run this command: 
.\WinTime64.exe -a -o log.txt .\exiftool.exe 
all is good and I get output.

if I rename the file and the argument is changed to exiftøl.exe like this:
.\WinTime64.exe -a -o log.txt .\exiftøl.exe
I get no output, is there any fix for this?

**Comment by cbielow** [comment]
Thanks for reporting!

I did not test unicode capabilities -- and it turns out Microsoft is making this a bit harder than it needs to be. Fix is coming up.

**Comment by cbielow** [comment]
fixed in current release:
https://github.com/cbielow/wintime/releases/tag/1.1.0

**Comment by sigurd-dev** [comment]
Thank you!
